version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/app/src
      - ./backend/requirements.txt:/app/requirements.txt
      - ./data:/app/data 
    restart: unless-stopped
