"""deleted embeddings and tags from book

Revision ID: 28cfd61ae9b7
Revises: 5ac9578ae0a5
Create Date: 2025-08-14 14:16:03.438092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28cfd61ae9b7'
down_revision: Union[str, Sequence[str], None] = '5ac9578ae0a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
