"""deleted embeddings and tags from book

Revision ID: 5ac9578ae0a5
Revises: d5b1fea3ad56
Create Date: 2025-08-14 13:08:45.467993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '5ac9578ae0a5'
down_revision: Union[str, Sequence[str], None] = 'd5b1fea3ad56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'embedding')
    op.drop_column('books', 'embedding_tags')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('embedding_tags', sqlite.JSON(), nullable=True))
    op.add_column('books', sa.Column('embedding', sa.BLOB(), nullable=True))
    # ### end Alembic commands ###
