"""Add embedding_emotions to Music

Revision ID: 67b02c077546
Revises: d6597222476b
Create Date: 2025-08-18 17:57:04.638361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67b02c077546'
down_revision: Union[str, Sequence[str], None] = 'd6597222476b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('music', sa.Column('embedding_emotions', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('music', 'embedding_emotions')
    # ### end Alembic commands ###
