"""changed music.py

Revision ID: a0b44b44e1ac
Revises: cc974d36c0b1
Create Date: 2025-07-25 16:52:01.532158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0b44b44e1ac'
down_revision: Union[str, Sequence[str], None] = 'cc974d36c0b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('music', 'link')
    op.drop_column('music', 'spotify_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('music', sa.Column('spotify_url', sa.VARCHAR(), nullable=True))
    op.add_column('music', sa.Column('link', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
