"""deleted book_fragment

Revision ID: d5b1fea3ad56
Revises: 894fce3cab5c
Create Date: 2025-08-13 19:00:41.785404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'd5b1fea3ad56'
down_revision: Union[str, Sequence[str], None] = '894fce3cab5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_fragments')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_fragments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('book_id', sa.INTEGER(), nullable=True),
    sa.Column('fragment_index', sa.INTEGER(), nullable=True),
    sa.Column('embedding', sa.BLOB(), nullable=True),
    sa.Column('tag_embedding', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
