"""changes spotify features to JSON

Revision ID: f810559e594d
Revises: a0b44b44e1ac
Create Date: 2025-07-26 15:48:17.137918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f810559e594d'
down_revision: Union[str, Sequence[str], None] = 'a0b44b44e1ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('music', sa.Column('spotify_features', sa.JSON(), nullable=True))
    op.drop_column('music', 'speechiness')
    op.drop_column('music', 'energy')
    op.drop_column('music', 'acousticness')
    op.drop_column('music', 'danceability')
    op.drop_column('music', 'liveness')
    op.drop_column('music', 'tempo')
    op.drop_column('music', 'valence')
    op.drop_column('music', 'instrumentalness')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('music', sa.Column('instrumentalness', sa.FLOAT(), nullable=True))
    op.add_column('music', sa.Column('valence', sa.FLOAT(), nullable=True))
    op.add_column('music', sa.Column('tempo', sa.FLOAT(), nullable=True))
    op.add_column('music', sa.Column('liveness', sa.FLOAT(), nullable=True))
    op.add_column('music', sa.Column('danceability', sa.FLOAT(), nullable=True))
    op.add_column('music', sa.Column('acousticness', sa.FLOAT(), nullable=True))
    op.add_column('music', sa.Column('energy', sa.FLOAT(), nullable=True))
    op.add_column('music', sa.Column('speechiness', sa.FLOAT(), nullable=True))
    op.drop_column('music', 'spotify_features')
    # ### end Alembic commands ###
